language: perl
perl:
    #- dev
    - "blead"
    #- stable
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test User"
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
  - cpanm -n Code::TidyAll Pod::Tidy
  - build-dist
  - cd $BUILD_DIR
install:
  - sudo apt-get update
  - sudo apt-get install ispell nodejs php5-cli
  - cpan-install ExtUtils::MakeMaker~6.68 --deps
script:
  - perl Makefile.PL
  - make
  - prove -br -j$(test-jobs) $(test-files)
notifications:
  email:
    recipients:
      - autarch@urth.org
    on_success: change
    on_failure: always
