---
language: perl
perl:
  - blead
  - dev
  - 5.22
  - 5.20
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10
  - 5.8
matrix:
  allow_failures:
    - perl: blead
  include:
    - env: COVERAGE=1
      perl: 5.22
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test User"
  - sudo apt-get update
  - sudo apt-get install ispell nodejs php5-cli
  - eval $(curl https://travis-perl.github.io/init) --auto
